server:
  port: 8080

spring:
  application:
    name: stock-brokerage-app
  
  main:
    allow-circular-references: true

  # MongoDB Configuration
  data:
    mongodb:
      host: localhost
      port: 27017
      database: stock_brokerage
      auto-index-creation: true

  # Redis Configuration
  redis:
    host: localhost
    port: 6379
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0

  # Kafka Configuration
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
    consumer:
      group-id: stock-brokerage-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.stockbrokerage.events"
      auto-offset-reset: earliest

# JWT Configuration
jwt:
  secret: mySecretKey123456789012345678901234567890
  expiration: 86400000 # 24 hours in milliseconds

# Application Configuration
app:
  trading:
    market-hours:
      start: "09:30"
      end: "16:00"
    fees:
      per-trade: 0.99
      percentage: 0.001
  
  rate-limit:
    orders-per-minute: 10
    api-calls-per-minute: 100

# Finnhub API Configuration
finnhub:
  api:
    base-url: https://finnhub.io/api/v1
    token: d2pame1r01qnhraqb5s0d2pame1r01qnhraqb5sg
    websocket-url: wss://ws.finnhub.io
    rate-limit: 30 # 30 calls per second

# PayPal Configuration
paypal:
  client:
    id: Abjs4rnESL6Z8m18riVyXR7RAhHM-q1py-zd3cT7rlWFTrlEioLW6Ax5a8w1NelDqRHHwpwWCIA3ZZ14
    secret: EEybL2FyfEUfpM13C8xjodpyK9-UocX4e_Ery1B1VfL3IdKpqfsEqKboI6YCtpJWnK4S1yh8D58Wg87g
  mode: live
  return:
    success:
      url: http://localhost:8080/payment-success
    cancel:
      url: http://localhost:8080/payment-cancelled

logging:
  level:
    com.stockbrokerage: DEBUG
    org.springframework.kafka: INFO
    org.springframework.security: DEBUG